# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manaCost', models.CharField(max_length=40)),
                ('cmc', models.IntegerField()),
                ('typeString', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=400)),
                ('flavor', models.CharField(max_length=400)),
                ('artist', models.CharField(max_length=30)),
                ('number', models.IntegerField()),
                ('power', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('layout', models.CharField(max_length=20)),
                ('multiverseid', models.IntegerField()),
                ('imageName', models.CharField(max_length=50)),
                ('cardid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cardtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10)),
                ('releaseDate', models.CharField(max_length=15)),
                ('border', models.CharField(max_length=7)),
                ('settype', models.CharField(max_length=15)),
                ('block', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supertype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='cardset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='CardsApp.Set'),
        ),
        migrations.AddField(
            model_name='card',
            name='colors',
            field=models.ManyToManyField(related_name='colors', to='CardsApp.Color'),
        ),
        migrations.AddField(
            model_name='card',
            name='subtypes',
            field=models.ManyToManyField(related_name='subtypes', to='CardsApp.Subtype'),
        ),
        migrations.AddField(
            model_name='card',
            name='supertypes',
            field=models.ManyToManyField(related_name='supertypes', to='CardsApp.Supertype'),
        ),
        migrations.AddField(
            model_name='card',
            name='types',
            field=models.ManyToManyField(related_name='types', to='CardsApp.Cardtype'),
        ),
    ]
