# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardsApp', '0002_auto_20170217_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='power',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='toughness',
            field=models.IntegerField(null=True),
        ),
    ]
