# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardsApp', '0004_auto_20170217_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='manaCost',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
