# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardsApp', '0005_auto_20170217_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='flavor',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
