# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardsApp', '0007_auto_20170217_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='block',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='border',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='releaseDate',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='settype',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
